apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: pod-exception
  namespace: delta
spec:
  exceptions:
  - policyName: limit-containers
    ruleNames:
    - limit-containers-per-pod
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - delta
        names:
        - three-container-pod*
