apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: main-app
      image: nginx
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
    - name: sidecar-container
      image: nginx
      ports:
        - containerPort: 9090
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.25"
          memory: "128Mi"
    - name: another-sidecar-container
      image: nginx
      ports:
        - containerPort: 9091
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.25"
          memory: "128Mi"

